/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

/**
 *
 * @author frans
 */
public class VentanaInicial extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicial
     */
    private everySede sede;
    public VentanaInicial(everySede sede) {
        initComponents();
        this.sede = sede;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        agregarNuevaSede = new javax.swing.JButton();
        agregarNuevoCiudadano = new javax.swing.JButton();
        eliminarSede = new javax.swing.JButton();
        eliminarCiudadano = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Exportar = new javax.swing.JButton();
        opcionesMostrar = new javax.swing.JButton();
        Importar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Menú");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione la opción a realizar");

        agregarNuevaSede.setText("Agregar Sede");
        agregarNuevaSede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarNuevaSedeMouseClicked(evt);
            }
        });
        agregarNuevaSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarNuevaSedeActionPerformed(evt);
            }
        });

        agregarNuevoCiudadano.setText("Agregar Ciudadano");
        agregarNuevoCiudadano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarNuevoCiudadanoMouseClicked(evt);
            }
        });
        agregarNuevoCiudadano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarNuevoCiudadanoActionPerformed(evt);
            }
        });

        eliminarSede.setText("Eliminar Sede");
        eliminarSede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarSedeMouseClicked(evt);
            }
        });
        eliminarSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarSedeActionPerformed(evt);
            }
        });

        eliminarCiudadano.setText("Eliminar Ciudadano");
        eliminarCiudadano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarCiudadanoMouseClicked(evt);
            }
        });
        eliminarCiudadano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCiudadanoActionPerformed(evt);
            }
        });

        Salir.setText("Cerrar");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Exportar.setText("Exportar datos");
        Exportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExportarMouseClicked(evt);
            }
        });
        Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarActionPerformed(evt);
            }
        });

        opcionesMostrar.setText("Mostrar");
        opcionesMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcionesMostrarMouseClicked(evt);
            }
        });
        opcionesMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesMostrarActionPerformed(evt);
            }
        });

        Importar.setText("Importar archivo");
        Importar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImportarMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/voto.jpg"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Salir)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(opcionesMostrar)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(agregarNuevaSede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eliminarSede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Exportar))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Importar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarCiudadano, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarNuevoCiudadano, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarNuevaSede)
                    .addComponent(agregarNuevoCiudadano))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarSede)
                    .addComponent(eliminarCiudadano))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exportar)
                    .addComponent(Importar))
                .addGap(32, 32, 32)
                .addComponent(opcionesMostrar)
                .addGap(4, 4, 4)
                .addComponent(Salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarCiudadanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCiudadanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarCiudadanoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void agregarNuevaSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarNuevaSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarNuevaSedeActionPerformed

    private void agregarNuevoCiudadanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarNuevoCiudadanoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_agregarNuevoCiudadanoActionPerformed

    private void eliminarSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarSedeActionPerformed

    private void ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExportarActionPerformed

    private void opcionesMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesMostrarActionPerformed

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void agregarNuevaSedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarNuevaSedeMouseClicked
        // TODO add your handling code here:
        VentanaAgregarSede ventana = new VentanaAgregarSede(sede);
        ventana.setVisible(true);
    }//GEN-LAST:event_agregarNuevaSedeMouseClicked

    private void agregarNuevoCiudadanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarNuevoCiudadanoMouseClicked
        // TODO add your handling code here:
        VentanaAgregarCiudadano ventana = new VentanaAgregarCiudadano(sede);
        ventana.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_agregarNuevoCiudadanoMouseClicked

    private void eliminarSedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarSedeMouseClicked
        // TODO add your handling code here:
        //VentanaEliminarSede ventana = new VentanaEliminarSede(sede);
        //ventana.setVisible(true);
    }//GEN-LAST:event_eliminarSedeMouseClicked

    private void eliminarCiudadanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarCiudadanoMouseClicked
        // TODO add your handling code here:
        EliminarCiudadano ventana = new EliminarCiudadano(sede);
        ventana.setVisible(true);
    }//GEN-LAST:event_eliminarCiudadanoMouseClicked

    private void ExportarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ExportarMouseClicked

    private void ImportarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ImportarMouseClicked

    private void opcionesMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionesMostrarMouseClicked
        // TODO add your handling code here:
        VentanaMostrar ventana = new VentanaMostrar(sede);
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_opcionesMostrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                everySede sede = new everySede();
                new VentanaInicial(sede).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exportar;
    private javax.swing.JButton Importar;
    private javax.swing.JButton Salir;
    private javax.swing.JButton agregarNuevaSede;
    private javax.swing.JButton agregarNuevoCiudadano;
    private javax.swing.JButton eliminarCiudadano;
    private javax.swing.JButton eliminarSede;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton opcionesMostrar;
    // End of variables declaration//GEN-END:variables
}
